spring:
  application:
    name: asignaturas-servicio
  data:
    mongodb:
      uri: mongodb://localhost:27017/usuariosdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082