version: '3.8'
services:

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=default

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  usuarios-servicio:
    build: ./usuarios-servicio
    container_name: usuarios-servicio
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
      - mongo

  asignaturas-servicio:
    build: ./asignaturas-servicio
    container_name: asignaturas-servicio
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server
      - mongo

  matriculas-servicio:
    build: ./matriculas-servicio
    container_name: matriculas-servicio
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server
      - mongo

volumes:
  mongo_data: