server:
  port: 8082

spring:
  application:
    name: asignaturas-servicio
  data:
    mongodb:
      uri: mongodb://localhost:27017/asignaturasdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka