
server:
  port: 8081

spring:
  application:
    name: usuarios-servicio
  data:
    mongodb:
      uri: mongodb://localhost:27017/usuariosdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: mySecretKey123456
  expiration: 3600000  # 1 hora en milisegundos
