
server:
  port: 8083

spring:
  application:
    name: matriculas-servicio
  data:
    mongodb:
      uri: mongodb://localhost:27017/matriculasdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
